### ISSUE TITLE
What is AppBar For?

### ISSUE THREAD

**Issue by pjhjohn** [gnujoow/shim#2]
Currently, there is no working feature goes with `AppBar`.

However, assuming the `AppBar` does nothing, why don't you get rid of it? It looks better without Appbar to make `Clock` and `Quote` more focusable.

**Comment by gnujoow** [comment]
`AppBar`(NavBar component) has no function at the moment.

some functions such as Todo List, weekly weather will be added shortly. But the thing is I haven't made a decision where I put these features in the app. I'm considering to place `Appbar` or `BottomNavigation`. what do offer better UX of two? I want to hear your thought.

thanks for opening the issue. @pjhjohn

**Comment by pjhjohn** [comment]
I think it's time to decide the key feature of this extension. For me to think, the key feature is (comfortable)`image`, `time`, and `quotes`.

To make first things first, I suggest rather putting neither `BottomNavigation` nor `AppBar` because it consumes entire width of the screen. I think it's **attractive enough to convince users to take a serious look at'em**. If that's your intention, let's try it. Otherwise, simple button with icon & text will be fine, like `FlatButton` from material-ui that has transparent background

**Comment by gnujoow** [comment]
I've though about this issure for a day and I end up with a conclusion the app with out `AppBar` is better untill some features are made. Thanks for your suggestion @pjhjohn

Now the problem is what features is in the app. Just showing some quotes, daily weather and todoList are very similar to [Momentum](https://momentumdash.com/). And making a mimic app is not exciting :(.

To make this project practical, it's important to define that what the app is for. Any Idea?
